//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libsys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.BorrowBooks = new HashSet<BorrowBook>();
        }
    
        public int studentID { get; set; }
        public string studentName { get; set; }
        public string studentFatherName { get; set; }
        public string studentAddress { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public string userToken { get; set; }
        public Nullable<int> studentAge { get; set; }
        public Nullable<int> studentYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowBook> BorrowBooks { get; set; }
    }
}
